name: boltz_dart_example
description: "Demonstrates how to use the boltz_dart plugin."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  boltz_dart:
    path: ../ 
    # git:
    #   url: https://github.com/SatoshiPortal/boltz-dart.git
    #   ref: trunk
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
